<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>

    <groupId>build.jenesis.demo</groupId>
    <artifactId>java-pom-executable</artifactId>
    <version>1.0.0</version>

    <build>
        <sourceDirectory>sources</sourceDirectory>
    </build>

    <properties>
        <mainClass>sample.Sample</mainClass>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>3.14.0</version>
                <!--Checksum/SHA-256/7b96bf3ee68949abb5bc465559ac270e0551596fa34523fddf890ec418dde13c-->
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.14.0</version>
        </dependency>
    </dependencies>
    <!--jenesis.pin
    launcher/maven/build.jenesis/build.jenesis.launcher 0.3.1 SHA-256/720f9c1710ce6d498c2591f11d365423b9f1b76190d1bdca6920f381c32bf05c
    -->
</project>
